spring.datasource.url=jdbc:postgresql://db.dnzxokdcnjcbbruvgghr.supabase.co:5432/postgres?user=postgres&password=Ilovesupabase007$
spring.datasource.username=postgres
spring.datasource.password=Ilovesupabase007$
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=VjZsUSF1OXBAMWJBcXolYTVHbUNoSDd6MyQ1bEVveDIrSnpZdzlydDJBcTNzTGgkRDlaVCtRPT0=

# HikariCP settings
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
